---
name: Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Run commands
        run: |
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: omero-ms-image-region_${{ matrix.java }}
          path: build/distributions/*
  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        java: [11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
      - name: Create a release and upload Release Assets
        run:  |
          version=$(./gradlew properties | grep ^version:)
          tag=${GITHUB_REF#refs/*/}
          javaversions=("8" "11")
          for jv in ${javaversions[@]}; do
            dir=omero-ms-image-region_$jv
            for file in "$dir"/*
            do
              if [ -f "$file" ];then
                filename=$(basename -- "$file")
                #extension="${filename##*.}"
                # name="${filename%.*}"
                # newname="${name}_b${{github.run_number}}.${extension}"
                # newname="${name}.${extension}"
                # echo $newname
                # mv $dir/$filename $dir/$newname
                sha256sum $dir/$filename >> SHASUMS
              fi
            done
          done
          gh release create $tag $dir/*.zip $dir/*.tar SHASUMS --title "$title" --notes-from-tag
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
